# some common configuration for all services
x-deploy-config:  &deploy-default-config
  restart_policy:
    condition: none
  resources:
    limits:
      memory: 1G

# starts the compose file c:
version: "3"
services:
  ipfs-default-nodes:
    image: jamesfurtado/example-amd64
    networks: [ ipfs-network ]
    env_file: [ .env ]
    deploy:
      <<: *deploy-default-config
      replicas: ${TOTAL_REPLICAS:?Missing replicas number}
    depends_on:
      - ipfs-default-bootstrap:

  ipfs-default-bootstrap:
    image: cluster-example
    networks: [ ipfs-network ]
    env_file: [ .env ]
    deploy:
      <<: *deploy-default-config
      replicas: ${TOTAL_REPLICAS:?Missing replicas number}


networks:
  ipfs-network:
    driver: overlay
