# starts the compose file c:
version: "3"
services:
  base-service:
    image: ipfs-tests
    cap_add:
      - NET_ADMIN
    networks: 
      - ipfs-network
    env_file: 
      - ../.ipfs-env
    volumes:
      - ${SHARED_DIR}:${EXP_SHARED_DIR}
    deploy:
      restart_policy:
        condition: none
      resources:
        limits:
          memory: 1G
