version: "3"
services:
  example:
    image: jamesfurtado/example-amd64
    networks:
      - example-network
    deploy:
      replicas: 20
      restart_policy:
        condition: none
networks:
  example-network:
    driver: overlay
