# starts the compose file c:
version: "3"
services:
  default-nodes:
    extends:
      file: common.yml
      service: base-service 
    environment:
      - NODE_MODE=default
      - NODE_ROLE=worker
    deploy:
      replicas: ${EXP_TOTAL_WORKER_NODES:?Missing number of worker nodes}
    depends_on:
      - bootrap-nodes

  bootrap-nodes:
    extends:
      file: common.yml
      service: base-service 
    environment:
      - NODE_MODE=default
      - NODE_ROLE=bootstrap
    deploy:
      replicas: ${EXP_TOTAL_BOOT_NODES:?Missing number of bootstrap nodes}
  
networks:
  ipfs-network:
    driver: overlay