# starts the compose file c:
version: "3"
services:
  default-nodes:
    extends:
      file: base.yml
      service: base-service 
    enviroment:
      - NODE_MODE=default
      - NODE_ROLE=worker
    deploy:
      replicas: ${TOTAL_WORKER_NODES:?Missing number of worker nodes}

  bootrap-nodes:
    extends:
      file: base.yml
      service: base-service 
    enviroment:
      - NODE_MODE=default
      - NODE_ROLE=bootstrap
    deploy:
      replicas: ${TOTAL_BOOTSTRAP_NODES:?Missing number of bootstrap nodes}
  
networks:
  ipfs-network:
    driver: overlay

# volumes:
#   ipfs-volume:
#     - ${SHARED_VOLUME}:${EXP_SHARED_VOLUME}
