# starts the compose file c:
x-deploy: &deploy-cfg
  restart_policy:
    condition: none
  resources:
    limits:
      memory: 1G

x-base-service: &base-service
    image: ipfs-tests
    cap_add:
      - NET_ADMIN
    networks: 
      - ipfs-network
    env_file: 
      - ../.ipfs-env
    volumes:
      - ${SHARED_DIR}:${EXP_SHARED_DIR}

version: "3"
services:
  normal-nodes:
    <<: *base-service
    environment:
      - NODE_MODE=normal
      - NODE_ROLE=worker
    deploy:
      <<: *deploy-cfg
      replicas: ${EXP_NORMAL_NODES:?Missing number of normal worker nodes}
    depends_on:
      - secure-bootrap-nodes
      - normal-bootrap-nodes

  secure-nodes:
    <<: *base-service
    environment:
      - NODE_MODE=secure
      - NODE_ROLE=worker
    deploy:
      <<: *deploy-cfg
      replicas: ${EXP_SECURE_NODES:?Missing number of secure worker nodes}
    depends_on:
      - secure-bootrap-nodes
      - normal-bootrap-nodes

  normal-bootrap-nodes:
    <<: *base-service
    environment:
      - NODE_MODE=normal
      - NODE_ROLE=bootstrap
    deploy:
      <<: *deploy-cfg
      replicas: ${EXP_NORMAL_BOOT_NODES:?Missing number of normal bootstrap nodes}

  secure-bootrap-nodes:
    <<: *base-service
    environment:
      - NODE_MODE=secure
      - NODE_ROLE=bootstrap
    deploy:
      <<: *deploy-cfg
      replicas: ${EXP_SECURE_BOOT_NODES:?Missing number of secure bootstrap nodes}
  
networks:
  ipfs-network:
    driver: overlay
    ipam:
      config:
        - subnet: ${EXP_NETWORK_SUBNET?missing network subnet}